# -*- coding: utf-8 -*-
"""LTD DASHBOARDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vYiwvP4hJvnpDQnWly6hX84WHTyRC3ev
"""

import pandas as pd
import numpy as np
import plotly.offline as py
import plotly.graph_objs as go
import statistics as st

py.init_notebook_mode(connected=False)


# Devido o Plotly estar sendo utilizado no Google Collab, precisaremos definir
# a função abaixo e chamá-la sempre que quisermos exibir um gráfico


def enable_plotly_in_cell():
    import IPython
    display(IPython.core.display.HTML('''
    <script src="/static/components/requirejs/require.js"></script>
            <script>
            requirejs.config({
              paths: {
                base: '/static/base',
                plotly: 'https://cdn.plot.ly/plotly-1.5.1.min.js?noext',
             },
           });
          </script>
          '''))
    py.init_notebook_mode(connected=False)


# Definindo module pd para ler o banco de dados (Excel)
df = pd.read_csv(
    'https://docs.google.com/spreadsheets/d/e/2PACX-1vRy0Q'
    '-l3QROQtL8xtEzY6eQiuEiqgbPNte4XVBWd09Nj3jBCU15VRMtapzqRjQHRaW7qcJDFwGdUqV5/pub?output=csv')

# Gráfico: histograma!
# chama-se a função ploty in cell, para exibir o gráficos:
enable_plotly_in_cell()

# Parâmetros das colunas ("histo1") do histograma:
histo1 = go.Bar(x=df['horario'],
                y=df['atendimento'],
                name='Exemplo 1')
data = [histo1]

# Parâmetros do Layout do gráfico "hsto1":
layout = go.Layout(title='Exemplo de Gráfico Histograma<br><sup>Eixo Y, média: {:.2f}, mediana {:.2f}, '
                         'moda {:.2f}</sup>'.format(
                          st.mean(df['atendimento'].dropna()),
                          st.median(df['atendimento'].dropna()),
                          st.mode(df['atendimento'].dropna())
                                                    ),
                   yaxis={'title': 'Eixo Y'},
                   xaxis={'title': 'Eixo X'})
fig = go.Figure(data=data, layout=layout)
py.iplot(fig)

# Gráfico: Pizza!
# Estabelecendo cores que serão usadas nas fatias do gráfico:
colors = ['gold', 'mediumturquoise', 'darkorange', 'lightgreen']

# Parâmetros das fatias da pizza "fig":
fig = go.Pie(labels=df['listas'],
             values=df['exemplos pizza'],
             hole=.3,
             pull=df['relevancia'],
             insidetextorientation='radial')
data = [fig]

# Parâmetros do Layout do gráfico de pizza (fig)!
layout = go.Layout(title=' Exemplo de Gráfico de Pizza')
fig = go.Figure(data=data, layout=layout)

# Parâmetro cores e contorno do gráfico de pizza (fig)!
fig.update_traces(hoverinfo='label+percent', textinfo='label+percent', textfont_size=10,
                  marker=dict(colors=colors, line=dict(color='#000000', width=2)))

# Configuração dos parâmetros da resolução do gráfico de pizza (fig)!
fig.update_layout(
    autosize=True
)

py.iplot(fig)

# Gráfico: Linhas!
# Parâmetros das linhas:
# Parâmetros da linha (Scatter) "trace1" (marcador):
trace1 = go.Scatter(x=df['meses do ano'],
                    y=df['nums linha 1'],
                    mode='lines',
                    name='Exemplo 1',
                    line={'color': '#341f97',
                          'dash': 'dash'})

# Parâmetros da linha (Scatter) "trace2" (linha pontilhada):
trace2 = go.Scatter(x=df['meses do ano'],
                    y=df['nums linha 2'],
                    mode='lines',
                    name='Exemplo 2',
                    line={'color': '#FF4433',
                          'dash': 'dot'})

# Parâmetros da linha (Scatter) "trace3" (linha tracejada):
trace3 = go.Scatter(x=df['meses do ano'],
                    y=df['nums linha 3'],
                    mode='markers+lines',
                    name='Exemplo 3',
                    line={'color': '#008000'})

data = [trace1, trace2, trace3]

# Parâmetros do Layout do gráfico:
layout = go.Layout(title=' Exemplo de Gráfico de Linhas',
                   yaxis={'title': 'Eixo Y'},
                   xaxis={'title': 'Eixo X'})
fig = go.Figure(data=data, layout=layout)
py.iplot(fig)

# Gráfico: Colunas!
# Parâmetros da coluna "colu1" (azul):
colu1 = go.Bar(x=df['exemplo colunas'],
               y=df['exemplo colunas'],
               name='Exemplo 1')

# Parâmetros da coluna "colu2" (vermelho):
colu2 = go.Bar(x=df['nums coluna'],
               y=df['nums coluna'],
               name='Exemplo 2')

data = [colu1, colu2]

# Parâmetros do Layout do gráfico:
layout = go.Layout(title=' Exemplo de Gráfico de Colunas',
                   yaxis={'title': 'Eixo Y'},
                   xaxis={'title': 'Eixo X'})
fig = go.Figure(data=data, layout=layout)
py.iplot(fig)