# -*- coding: utf-8 -*-
"""Teste 2 LTD projeto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQibeW5Exgr_6aTEfxAj6OkfXSh8t3TN
"""

import pandas as pd
import numpy as np
import plotly.offline as py
import plotly.graph_objs as go

py.init_notebook_mode(connected=False)

# Devido o Plotly estar sendo utilizado no Google Collab, precisaremos definir
# a função abaixo e chamá-la sempre que quisermos exibir um gráfico

def enable_plotly_in_cell():
  import IPython
  display(IPython.core.display.HTML('''
  <script src="/static/components/requirejs/require.js"></script>
          <script>
          requirejs.config({
            paths: {
              base: '/static/base',
              plotly: 'https://cdn.plot.ly/plotly-1.5.1.min.js?noext',
            },
          });
        </script>
        '''))
  py.init_notebook_mode(connected=False)

#Definindo module pd para ler o banco de dados (Excel)
df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRy0Q-l3QROQtL8xtEzY6eQiuEiqgbPNte4XVBWd09Nj3jBCU15VRMtapzqRjQHRaW7qcJDFwGdUqV5/pub?output=csv')
df.head()



#Gráfico: histograma! --------------------------------------------------------//



enable_plotly_in_cell()

#Parâmetros das colunas do histograma:
histo1 = go.Bar(x = df['horario'],
                y = df['atendimento'],
                name = 'Exemplo 1')
data = [histo1]

#Parâmetros do Layout do gráfico
layout = go.Layout(title=' Exemplo de Gráfico Histograma',
                   yaxis={'title':'Eixo Y'},
                   xaxis={'title': 'Eixo X'})
fig = go.Figure(data=data, layout=layout)
py.iplot(fig)



#Gráfico: Pizza! -------------------------------------------------------------//



enable_plotly_in_cell()

#Estabelecendo cores que serão usadas em segmentos do gráfico
colors = ['gold', 'mediumturquoise', 'darkorange', 'lightgreen']

#Parâmetros do gráfico:
fig = go.Pie(labels=['exemplo1', 'exemplo2', 'exemplo3', 'exemplo4', 'exemplo5', 'exemplo6', 'exemplo7','exemplo8',
                     'exemplo9', 'exemplo10', 'exemplo11', 'exemplo12', 'exemplo13', 'exemplo14', 'exemplo15', 'exemplo16',
                     'exemplo17', 'exemplo18', 'outros'],
             values= df['exemplos'],
             hole=.0,
             pull=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2],
             insidetextorientation='radial')
data = [fig]

#Parâmetros do Layout do gráfico
layout = go.Layout(title=' Exemplo de Gráfico de Pizza')
fig = go.Figure(data=data, layout=layout)

#Parâmetro cores e contorno do gráfico de pizza!
fig.update_traces(hoverinfo='label+percent', textinfo='label+percent', textfont_size=10,
                  marker=dict(colors=colors, line=dict(color='#000000', width=0)))
py.iplot(fig)



#Gráfico: Linhas! ------------------------------------------------------------//



enable_plotly_in_cell()

#Parâmetros do Gráfico de linhas (marcador)
trace1 = go.Scatter(x = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio'],
                    y = df['exemplos'],
                    mode = 'lines',
                    name = 'Exemplo 1',
                    line = {'color': '#341f97',
                            'dash': 'dash'})

#Parâmetros do Gráfico de linhas (linha pontilhada)
trace2 = go.Scatter(x = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio'],
                    y = df['outros'],
                    mode = 'lines',
                    name = 'Exemplo 2',
                    line = {'color': '#FF4433',
                            'dash': 'dot'})

#Parâmetros do Gráfico de linhas (linha tracejada)
trace3 = go.Scatter(x = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio'],
                    y = df['nums'],
                    mode = 'markers+lines',
                    name = 'Exemplo 3',
                    line = {'color': '#008000'})

data = [trace1, trace2, trace3]

#Parâmetros do Layout do gráfico
layout = go.Layout(title=' Exemplo de Gráfico de Linhas',
                   yaxis={'title':'Eixo Y'},
                   xaxis={'title': 'Eixo X'})
fig = go.Figure(data=data, layout=layout)
py.iplot(fig)



#Gráfico: de colunas! --------------------------------------------------------//



enable_plotly_in_cell()

#Parâmetros do Gráfico de Colunas 1 (azul)
histo1 = go.Bar(x = df['pessoas'],
                y = df['pessoas'],
                name = 'Exemplo 1')

#Parâmetros do Gráfico de Colunas 2 (vermelho)
histo2 = go.Bar(x = df['Idade'],
                y = df['Idade'],
                name = 'Exemplo 2')

data = [histo1, histo2]

#Parâmetros do Layout do gráfico
layout = go.Layout(title=' Exemplo de Gráfico de Colunas',
                   yaxis={'title':'Eixo Y'},
                   xaxis={'title': 'Eixo X'})
fig = go.Figure(data=data, layout=layout)
py.iplot(fig)

