# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jEqS6CNc2766OHujAEZv6V6hIUU9Zqjm
"""

import pandas as pd
import numpy as np
import plotly.offline as py
import plotly.graph_objs as go

py.init_notebook_mode(connected=False)

# Devido o Plotly estar sendo utilizado no Google Collab, precisaremos definir
# a função abaixo e chamá-la sempre que quisermos exibir um gráfico

def configure_plotly_browser_state():
  import IPython
  display(IPython.core.display.HTML('''
        <script src="/static/components/requirejs/require.js"></script>
        <script>
          requirejs.config({
            paths: {
              base: '/static/base',
              plotly: 'https://cdn.plot.ly/plotly-1.5.1.min.js?noext',
            },
          });
        </script>
        '''))

df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRy0Q-l3QROQtL8xtEzY6eQiuEiqgbPNte4XVBWd09Nj3jBCU15VRMtapzqRjQHRaW7qcJDFwGdUqV5/pub?output=csv')
df.head()

#Gráfico: histograma!
configure_plotly_browser_state()

histo1 = go.Bar(x = df['horario'],
                y = df['atendimento'])

data = [histo1]
py.iplot(data)

#Gráfico: Pizza!
configure_plotly_browser_state()

fig = go.Pie(labels=['exemplo1', 'exemplo2', 'exemplo3', 'exemplo4', 'exemplo5', 'exemplo6', 'outros'],
             values= df['exemplos'],
             hole=.3,
             pull=[0, 0],
             name="teste")

data = [fig]
py.iplot(data)

#Gráfico: Linhas!
configure_plotly_browser_state()

# Gráfico usando apenas marcadores
trace1 = go.Scatter(x = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio'],
                    y = df['exemplos'],
                    mode = 'lines',
                    name = 'Apenas marcadores',
                    line = {'color': '#341f97',
                            'dash': 'dash'})

# Gráfico de apenas linhas
trace2 = go.Scatter(x = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio'],
                    y = df['outros'],
                    mode = 'lines',
                    name = 'Apenas linhas',
                    line = {'color': '#341f97',
                            'dash': 'dot'})

# Criando gráfico com marcadores e linhas
trace3 = go.Scatter(x = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio'],
                    y = df['nums'],
                    mode = 'markers+lines',
                    name = 'Marcadores e Linhas',
                    line = {'color': '#008000'})

data = [trace1, trace2, trace3]

py.iplot(data)

#Gráfico: de colunas!
configure_plotly_browser_state()

histo1 = go.Bar(x = df['pessoas'],
               y = df['pessoas'])

histo2 = go.Bar(x = df['Idade'],
               y = df['Idade'])

data = [histo1, histo2]
py.iplot(data)